// <auto-generated />
using MeruTest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MeruTest.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20200501105435_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeruTest.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.HasKey("AreaId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            AreaId = 1,
                            AreaName = "West",
                            CityId = 1
                        },
                        new
                        {
                            AreaId = 2,
                            AreaName = "South",
                            CityId = 2
                        });
                });

            modelBuilder.Entity("MeruTest.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Mumbai",
                            State = "MH"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Banglore",
                            State = "KAR"
                        });
                });

            modelBuilder.Entity("MeruTest.Models.Customer", b =>
                {
                    b.Property<int>("CustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustMobNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubAreaId")
                        .HasColumnType("int");

                    b.HasKey("CustId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustId = 1,
                            Address = "Malad",
                            CustMobNo = "1234567890",
                            CustName = "Sachith",
                            SubAreaId = 1
                        },
                        new
                        {
                            CustId = 2,
                            Address = "Andheri",
                            CustMobNo = "1472583690",
                            CustName = "Suyash",
                            SubAreaId = 2
                        },
                        new
                        {
                            CustId = 3,
                            Address = "Kurla",
                            CustMobNo = "7894561230",
                            CustName = "Jeetu",
                            SubAreaId = 2
                        });
                });

            modelBuilder.Entity("MeruTest.Models.SubArea", b =>
                {
                    b.Property<int>("SubAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("SubAreaName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubAreaId");

                    b.ToTable("SubAreas");

                    b.HasData(
                        new
                        {
                            SubAreaId = 1,
                            AreaId = 1,
                            SubAreaName = "South West"
                        },
                        new
                        {
                            SubAreaId = 2,
                            AreaId = 2,
                            SubAreaName = "South"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
